### ISSUE TITLE
Using consistent way of ignoring JSON fields that works with booleans

### ISSUE THREAD

**Issue by aabdelzaher** [tanafaso/tanafaso-backend#117]
Currently, we name booleans as `isSomething`. This doesn't work with `@JsonIgnore` (https://github.com/FasterXML/jackson-annotations/issues/165), which is the way we use to ignore fields while serializing JSONs. Currently, we use `@JsonIgnoreProperties` when we want to ignore a boolean field and `@JsonIgnore` for the rest.

An enhancement would be to refactor the code to be consistent, possible ways to do this:
1) Changing naming convention for booleans to `something` instead of `isSomething`.
2) Using `@JsonIgnoreProperties` everywhere to ignore properties.
3) Using `Boolean` datatypes instead of `boolean`, but this will change the getters and setters to `getIsSomething` and `setIsSomething`.

**Comment by omaryasser** [comment]
Let's close this for now. I don't think I will work on it soon. I am trying to keep the issues with features that are most important to users and those who are good "first issues" to new contributers.
